version: "3"

services:

  app:
    image: catmaid/catmaid
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./volumes/app/static:/home/django/static
      - /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
      - DB_HOST=localhost
      - DB_USER=<catmaid-user>
      - DB_PASS=<catmaid-password>
      - DB_NAME=<catmaid-database>
      - DB_TUNE=false
      - CM_EXAMPLE_PROJECTS=true

  web:
    build: web
    restart: on-failure
    network_mode: "host"
    volumes:
      # This directory must have cert files
      - ./volumes/web/cert:/cert:ro
      - ./volumes/app/static:/static:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - app
